### ISSUE TITLE
Add a Lambda ARN output to the axiom-cloudwatch-lambda-cloudformation-stack.template.yaml

### ISSUE THREAD

**Issue by rschaefer-m1** [axiomhq/axiom-cloudwatch-lambda#46]
In order for other processes to be able to easily reference the created Lambda function (for example, the Backfiller and Subscriber cloudformation templates) it helps to expose the ARN of the created lambda function in axiom-cloudwatch-lambda-cloudformation-stack.template.yaml 

This can be done by adding the following code to the bottom of that template:
```
Outputs:
  LogsLambdaARN:
    Description: The ARN of the created Ingester Lambda
    Value: !GetAtt LogsLambda.Arn
```
